{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-photobiologywavebands
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/photobiologyWavebands_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/photobiologyWavebands/photobiologyWavebands_{{ version }}.tar.gz
  sha256: f2db97b3b21e309a614effe6623f3285b8f5eca552d68b06abc04b76a7d08a5c

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-photobiology >=0.9.13
  run:
    - r-base
    - r-photobiology >=0.9.13

test:
  commands:
    - $R -e "library('photobiologyWavebands')"           # [not win]
    - "\"%R%\" -e \"library('photobiologyWavebands')\""  # [win]

about:
  home: http://www.r4photobiology.info/, https://bitbucket.org/aphalo/photobiologywavebands
  license: GPL-2.0-or-later
  summary: Constructors of waveband objects for commonly used biological spectral weighting functions (BSWFs) and for different wavebands describing named ranges of wavelengths in the ultraviolet (UV), visible (VIS) and infrared (IR) regions of the electromagnetic spectrum.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
