# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o2IbNiAVYmuQ2KxM1CUciwUJFcsj/Kb5ytkWy3m46vJ52hTvbgujMQVhihFCljqQJwg2O6bZXJISJB3haUS1/DbUq2xhDmNnMTDZnsfvM5yNSP7K2fpZjD8BaP/NImhH+HtvmPLGUn7EfKJgdDtxtKU0oj7zfFxsYcgXJxfnKgzu5MinVJw688Fdak5BdDZcy8z9IgDctyulBwgKUi94Lv1EmUk4binSoPoAE9P5RwW5mhdbPABI1dZ307qkU7Y6/2MTfEyGPKzzIy9l+ZiJ5+C3JIdaVn2S7cHVTCJD2C0NgKypBxXb8tzJrxFWI7rOV3SuR08FnVeFRFxaTDNhRI2WpRzz9X6jIPyq+RGHS/4bKobjentAB/EpRxjsQrLEwh9HBpqNOu09T3m7G0GDxrMfwOaMHTVwLbde8hT8RS+W+QjMgvSlk+5O/ng2UTbfoVu0Qpx3wG8qvN/XEinjuC9tYZG1HGesyNSfbaTp9AUppY+NivvHgXDPUVwheBX4ZVIDWPO7YLXYG0P7c+uBZe/eb+/061OZO0gnmDIO3SI6p/OZxS6VCRp18abPwuoLLPZlFfH2XtUO68fb6aaaKdIwXDMqX77nWQPs6ZCobJNrNVxsfAknCu6qHMCedo2eznPQ+1khQSgj3h2ZkYnu7XW73gK4131VhEB/gQdTAZk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
