travis:
  secure:
    BINSTAR_TOKEN: TFCQVneaodLTUw3FpYjq5QGD4nd3z4oc+/PffRVRWGwOrIrK8oCO06j6IQOrAaPL8L4f0wgjJKzphBsKEPHJVF+GASbuL7jh0NmuqCOulxD85Zrmf43GJ0OE0JdfqAoAQllebQtHfVXa1juzOZW/ysIVHtNd/2A9g0c+2w/U07iTWfexso0A1NY3OXnojVqsZjGsWC1VqehzLUor34jg/SIvgE0Vfhpe/kExLu6GnVcDMwU2kM0OHZZSCzMm46Wd6PBgvcfapLoSkHxhgjMOQQV5F8hlt5Dt3gzVfcr6vM3bESVZU6RNpMJkltaQYj0RJvN37eLP67OKxLb4av7kWpim2mgQZLGrRRij7C8LJjWgljWBTKhFxdNyRC+iPe62syccVc295hF8odiJmjePFc3GOO/JnzeogCcoThLb1kTOnWoxy4VyLZd2kYpiA6kiMjDwevdwPXa699qqcF4rBoYe+W7+W3GLRl2miVsbNHL0urYTabFgQ6joN/FUtppMqkF3aeTKmsYy/lvZgli+QG/0kPIA7RN/NqDVfC/d4JLYqmpZOGysxaxgtL16oi90c2oQ5Pe0Y4FFMQ0svDIPh1gz/yhAQrMvs3G5wre8fBLFBzn3pAwOjlLj9EngvD6TsvHldt8ZYf3xRe9KxJFPT9NI2FSSz9rcMMyEwbsy6KI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
