travis:
  secure:
    BINSTAR_TOKEN: UFZqoWGF6963YciqxsCNGc29DQxfzJngpM3NlJl0x2X03FS497ReAiKQDYIj6LSoNPma1rVnLOxzdBCQ9rmjPf7E56cbtqSuIwiY8rPA8URmIbTlKeWi80vKDnLpzWBWmiIVlc8urtinb7t06RLQg7w6x8q+lnQCmQQq8j4eYtmPJihlgk2dcZUnSuHEWTIyLCk6C1pDYebU85HdeBLHJJY4tBHfzEcduHeH212NS5Hcq725JeHrqC9mb42JLBMbdcPnzfdfTmWH5vns8X5UgS4Sw74t/lQboq/pJQzJn2gl2C01vQ6IPNccPc07lZ47bi6CljDXyzUkQVZJ/HUFrk0IxVULbIRWprIUXbtxAa7aTroyqIOwj4JP7vQwGeU8d7TLM1lQIW/Azq0XrY7ZMsb0vwlQemcKwyjf8au2xWosKk/JeaE8uvszh+e9Uv8b2yfC0xiJ4Dbj9SXk+vwwNx5QAoxdWtYyfwhPTTElvF4ZVutOaeRhWjSxHbFfp2F9nAUavcWf2tBbcgnB5cYbFWcR2NlG9rWIISZUqKGf/XDFH2p7urW19NMil29PitjRcl6/fF808v9a+DaXEj0uWM6Hi0g8mjPub6THrVvC5+z+tSK3FmYl4XbpgGvzxid9Ntp3qQX2dgsO0ryivNQkBkXdiCahGryEG2TGeJxlk8I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
