appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: o2IbNiAVYmuQ2KxM1CUciwUJFcsj/Kb5ytkWy3m46vJ52hTvbgujMQVhihFCljqQJwg2O6bZXJISJB3haUS1/DbUq2xhDmNnMTDZnsfvM5yNSP7K2fpZjD8BaP/NImhH+HtvmPLGUn7EfKJgdDtxtKU0oj7zfFxsYcgXJxfnKgzu5MinVJw688Fdak5BdDZcy8z9IgDctyulBwgKUi94Lv1EmUk4binSoPoAE9P5RwW5mhdbPABI1dZ307qkU7Y6/2MTfEyGPKzzIy9l+ZiJ5+C3JIdaVn2S7cHVTCJD2C0NgKypBxXb8tzJrxFWI7rOV3SuR08FnVeFRFxaTDNhRI2WpRzz9X6jIPyq+RGHS/4bKobjentAB/EpRxjsQrLEwh9HBpqNOu09T3m7G0GDxrMfwOaMHTVwLbde8hT8RS+W+QjMgvSlk+5O/ng2UTbfoVu0Qpx3wG8qvN/XEinjuC9tYZG1HGesyNSfbaTp9AUppY+NivvHgXDPUVwheBX4ZVIDWPO7YLXYG0P7c+uBZe/eb+/061OZO0gnmDIO3SI6p/OZxS6VCRp18abPwuoLLPZlFfH2XtUO68fb6aaaKdIwXDMqX77nWQPs6ZCobJNrNVxsfAknCu6qHMCedo2eznPQ+1khQSgj3h2ZkYnu7XW73gK4131VhEB/gQdTAZk=
