travis:
  secure:
    BINSTAR_TOKEN: SLlw+JWOmXwhggUsoHfwLAfo0EYg54HoZ0d0TY+n0eKFJsGfjCKHhIdiC3j7L0dmCKZNpu7uJShWZ/9tnNps0Y9X/cowdPLRKtWiJtuuTg/7AcVZcU5FuKqfQoDvrVBC69JhIZ9ImGQMAltHph0lOa580e9IxXf1Y49P29HW7UbDZjHw98Jzj+eE6Y3mvwhGft3lCoXl9l+JJ/PI1RwxCtbjV7vbV/eE7sP9J+48B9ugXDp+rJCdeAdwlBH/iNAfl2JvMWPY6aJF6pt0sFvHBai4Gxpnx07wEa/K4UwfbAFo4XOLLLZ3MTltLA8lrgOgjj6HOAD2SiD8Sa706bQm0oXYw1HM/gW1a9Qct8wXO4dLv1ntIf0f2L5PB/GwJvF/Urfzlfha77Cie4E6qt8fOgA523xp2mU2aKG+R3WgFBUJKYR3XSWmNFzKAljVUBiKVIMx0eWeN2k75LWrbsiVKJKXaM+SzCgQPiRahvUmz7kaiWXZg4HkDySCOJ8WX+F4fbcNWZ5UjuK5V7wODKRqLRapRy6GHL1VsZYU7k6PBjhlFjoIc+euFMLk1Y7yEW13zuJUSrR5YseOalilaosfFu2hH/Oz9aSM/jXgCl5imoYXNe4SZXhgtIKEF4B5iBRcFubFtwhG7WwCmOGHFIZRStOYzD/oZ4glob5wwV4AyZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
